import re


def _extract_numbers(text: str):
    """
    Extract numeric values from text.

    Examples:
        ₹16,751,325 -> 16751325
        83.34%      -> 83.34
        41 orders   -> 41
    """

    if not text:
        return []

    matches = re.findall(
        r"(?<![\w.])\d[\d,]*(?:\.\d+)?",
        text,
    )

    numbers = []

    for value in matches:
        cleaned = value.replace(",", "").strip()

        if not cleaned:
            continue

        try:
            number = float(cleaned)

            if number.is_integer():
                number = int(number)

            numbers.append(number)

        except ValueError:
            continue

    return numbers


def _close(a, b, tolerance=0.01):
    return abs(float(a) - float(b)) <= tolerance


def validate_financial_values(
    answer: str,
    summaries: list,
) -> bool:
    """
    Validate financial/order numbers generated by the LLM
    against authoritative database summaries.

    Core DB values must match exactly.

    Derived financial values such as:
        - payment recovery %
        - outstanding %
        - differences
        - ratios

    are independently verified from the authoritative DB values.

    This prevents the LLM from confidently returning an
    incorrect financial number while still allowing it to
    explain derived metrics.
    """

    if not answer:
        return False

    if not summaries:
        return False

    # ============================================================
    # 1. Collect authoritative DB values
    # ============================================================

    expected_numbers = set()

    for summary in summaries:

        for key in (
            "orders",
            "invoice_total",
            "payment_total",
            "outstanding",
            "cancelled_orders",
            "pending_orders",
            "processing_orders",
        ):
            value = summary.get(key)

            if value is None:
                continue

            try:
                expected_numbers.add(float(value))

            except (TypeError, ValueError):
                continue

    # ============================================================
    # 2. Extract numbers from LLM response
    # ============================================================

    numbers = _extract_numbers(answer)

    # Qualitative answer with no numbers is valid.
    if not numbers:
        return True

    # ============================================================
    # 3. Build allowed derived values
    # ============================================================

    allowed_derived_numbers = set()

    for summary in summaries:

        invoice_total = summary.get("invoice_total")
        payment_total = summary.get("payment_total")
        outstanding = summary.get("outstanding")

        if invoice_total is None or payment_total is None:
            continue

        try:
            invoice_total = float(invoice_total)
            payment_total = float(payment_total)

        except (TypeError, ValueError):
            continue

        # --------------------------------------------------------
        # Payment recovery %
        # --------------------------------------------------------

        if invoice_total != 0:
            payment_recovery = (
                payment_total / invoice_total
            ) * 100

            allowed_derived_numbers.add(
                round(payment_recovery, 2)
            )

            # ----------------------------------------------------
            # Outstanding %
            # ----------------------------------------------------

            outstanding_percentage = (
                (invoice_total - payment_total)
                / invoice_total
            ) * 100

            allowed_derived_numbers.add(
                round(outstanding_percentage, 2)
            )

    # ============================================================
    # 4. Allow simple differences between authoritative values
    # ============================================================

    authoritative = list(expected_numbers)

    for index, first in enumerate(authoritative):

        for second in authoritative[index + 1:]:

            difference = abs(first - second)

            allowed_derived_numbers.add(
                round(difference, 2)
            )

    # ============================================================
    # 5. Validate every number
    # ============================================================

    for number in numbers:

        # Exact authoritative DB value.
        if any(
            _close(number, expected)
            for expected in expected_numbers
        ):
            continue

        # Valid derived financial value.
        if any(
            _close(number, derived)
            for derived in allowed_derived_numbers
        ):
            continue

        # Unknown number = potentially hallucinated.
        return False

    return True